### ISSUE TITLE
error occur when extracting training_data.zip

### ISSUE THREAD

**Issue by JongMokKim** [hmhtb/PID-Pavement-Image-Dataset#1]
Hello ! Thank you for sharing nice dataset!!

When I try to extract training_data.zip, the error occurs,,

could you please check again?

Thank you in advance!

**Comment by hmhtb** [comment]
Thanks for your intrest. 
You need to download all Training_data files and after that extract them together.

**Comment by JongMokKim** [comment]
Thank you for prompt response! 

I realize It was just my mistake

have a nice day :)
