### ISSUE TITLE
American Beauty Bag?

### ISSUE THREAD

**Issue by Lewington-pitsos** [hmhtb/PID-Pavement-Image-Dataset#4]
All the Labeling.partX.rar files are exactly the same size and, from my brief inspection, appear to contain exactly the same images. They also all each seem to contain a bunch of images of a plastic bag blowing in the wind.

@hmhtb do you think you could provide a little context on this? I'm very confused right now.

**Comment by hmhtb** [comment]
That should be related to your system. The files are checked and works good. try to use another PC

**Comment by Lewington-pitsos** [comment]
Haha, it's not a big deal, but there is DEFINITELY a video inside that RAR archive, and it's still there when I extract on other devices. 


![Screenshot from 2020-10-13 07-26-31](https://user-images.githubusercontent.com/24558325/95787957-4ad01000-0d26-11eb-8aa7-b0385e46d5d2.png)


Everything works good, it's just there's an extra video that probably doesn't need to be there.
